[extension]
name = "link-preview"
version = "0.1.0"
api_version = "1"

[datatypes]
declarations = []

[hooks]
declarations = ["link-preview.extract", "link-preview.fetch"]

[dependencies]
extensions = []
