[extension]
name = "watch"
version = "0.1.0"
api_version = "1"

[datatypes]
declarations = []

[hooks]
declarations = ["watch.set_ref", "watch.set_channel", "watch.check_ref_watchers", "watch.check_channel_watchers"]

[dependencies]
extensions = ["timeline", "reply-to"]
